import {Afacad_Flux} from "next/font/google"
import "./globals.css";
import Navbar from "@/components/Navbar.jsx";
import { Toaster } from "@/components/ui/sonner"
import { BusinessNameContext } from "@/context/BusinessNameContext";

const Afacad = Afacad_Flux({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  display: "swap",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={Afacad.className}
      >
        <BusinessNameContext>
          <Navbar />
          <Toaster />
          {children}
        </BusinessNameContext>
      </body>
    </html>
  );
}
